---
#This tasks mounts the share on sol to store the audits into

- name: mount_share |  Load Secrets
  include_vars: "secrets.yml"
  when: inventory_hostname in groups.local

- name: mount_share | Load Vars
  include_vars: "main.yml"
  when: inventory_hostname in groups.local

- name: mount_share | Make the directory to mount on
  file:
    path: /mnt/audits
    state: directory
  when: inventory_hostname in groups.local

- name: mount_share | Mount the shared drive
  mount:
    state: mounted
    path: /mnt/audits
    src: {{ share_drive }}
    fstype: cifs
    opts: "username={{ share_username }},domain={{ share_domain }},password={{ user_password }},vers=3.0"
  when: inventory_hostname in groups.local
  notify: unmount share
